services:
  redis:
    image: redis:7.4.2-alpine
    ports:
      - 127.0.0.1:6379:6379
    container_name: redis
  backend:
    image: go-backend
    build: ./example-backend
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: backend
  frontend:
    image: react-frontend
    build: ./example-frontend
    ports:
      - 127.0.0.1:5000:5000
    container_name: frontend